sudo: false
language: python
python:
  - "3.5"
env:
  matrix:
    # stdlib-pyethereum16
    - TOX_ENV=py27-stdlib-pyethereum16
    - TOX_ENV=py34-stdlib-pyethereum16
    - TOX_ENV=py35-stdlib-pyethereum16
    # stdlib-pyethereum20
    - TOX_ENV=py27-stdlib-pyethereum20
    - TOX_ENV=py34-stdlib-pyethereum20
    - TOX_ENV=py35-stdlib-pyethereum20
    # gevent-pyethereum16
    - TOX_ENV=py27-gevent-pyethereum16
    - TOX_ENV=py34-gevent-pyethereum16
    - TOX_ENV=py35-gevent-pyethereum16
    # gevent-pyethereum20
    - TOX_ENV=py27-gevent-pyethereum20
    - TOX_ENV=py34-gevent-pyethereum20
    - TOX_ENV=py35-gevent-pyethereum20
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install setuptools pip --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log
